alias java11='export JAVA_HOME=`/usr/libexec/java_home -v 11`'
alias java8='export JAVA_HOME=`/usr/libexec/java_home -v 1.8`'
alias java14='export JAVA_HOME=`/usr/libexec/java_home -v 14`'
alias java15='export JAVA_HOME=`/usr/libexec/java_home -v 15`'
alias java16='export JAVA_HOME=`/usr/libexec/java_home -v 16`'
alias sres1='git reset --soft HEAD~1'
alias sres2='git reset --soft HEAD~2'
alias sres3='git reset --soft HEAD~3'
alias sres4='git reset --soft HEAD~4'
alias sres5='git reset --soft HEAD~5'
alias co='git checkout'
alias st='git status'
alias stash='git stash'
alias rule='java -jar ~/Downloads/rule-api-1.24.2.1313.jar generate -rule'
alias upd_rules='java -jar ~/Downloads/rule-api-1.24.2.1313.jar update'
alias gpr='git pull --rebase'
alias gprm='git pull --rebase origin master'
alias up='cd ../'
alias jshell='/Library/Java/JavaVirtualMachines/jdk-16.jdk/Contents/Home/bin/jshell'
