alias java11='export JAVA_HOME=`/usr/libexec/java_home -v 11`'
alias java8='export JAVA_HOME=`/usr/libexec/java_home -v 1.8`'
alias gpr='git pull --rebase origin master'
alias java14='export JAVA_HOME=`/usr/libexec/java_home -v 14`'
alias sres1='git reset --soft HEAD~1'
alias co='git checkout'
alias st='git status'
alias rule='java -jar ~/Downloads/rule-api-1.24.2.1313.jar generate -rule'
alias upd_rules='java -jar ~/Downloads/rule-api-1.24.2.1313.jar update'
